# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('condition', models.IntegerField(choices=[(0, 'Over The Fucking Moon'), (1, 'Like Dancing'), (2, 'Excellent'), (5, 'Excited'), (10, 'Happy'), (15, 'Positive'), (20, 'Optimistic'), (25, 'Very Dude Like'), (27, 'Hungry'), (29, 'Tired'), (30, 'Bored'), (35, 'Pessimistic'), (40, 'Overwhelmed'), (45, 'Disappointed'), (50, 'Worried'), (55, 'Angry'), (60, 'Jelous'), (65, 'Insecure'), (70, 'Fear'), (75, 'Grief'), (80, 'Despair'), (85, 'Apathetic')])),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
